/**
 * ARIA Mission Control — Enhanced Approval Brief engine (Task 23).
 *
 * Every approval request carries an LLM-generated "owner brief" so the
 * operator can decide with full context:
 *
 *   WHY           — what the agent wants to do
 *   RISKS         — potential issues (list, with severity)
 *   IF APPROVED   — positive outcomes / next steps
 *   IF NOT        — consequences of denial
 *   CLARIFICATIONS — Q&A the owner might ask before deciding
 *
 * The brief is generated by `generateApprovalBrief()` and persisted as
 * JSON in `Approval.brief`. The owner can ask follow-up questions via
 * `discussApproval()` — answers are appended to `Approval.discussionLog`
 * so the full conversation trail is preserved.
 *
 * Oral confirmation: `oralConfirm()` analyzes a voice-call transcript
 * for affirmative phrases ("yes", "approved", "go ahead"). If found,
 * the approval is auto-approved (status="approved", oralConfirmed=true).
 *
 * `notifyOwner()` sends the brief via Telegram (or triggers a call) —
 * the operator can decide from their phone without opening the dashboard.
 *
 * This module is SERVER-ONLY (uses z-ai-web-dev-sdk via callLLM).
 */
import { db } from "./db";
import { callLLM } from "./llm-client";
import { logger } from "./logger";
import { sendTelegramMessage } from "./telegram-notifier";
import {
  parseJsonObject,
  parseJsonArray,
  toIso,
  ApprovalBriefSchema,
  type ApprovalBrief,
  type Approval,
  type ApprovalDiscussionEntry,
  type ApprovalRisk,
} from "./types";

// ─── Brief generation ────────────────────────────────────────────────

export interface BriefContext {
  /** Agent role generating the request (e.g. "CEO", "Sales"). */
  agentRole: string;
  /** Action verb (e.g. "deploy", "spend", "send_email", "sign_contract"). */
  action: string;
  /** Action arguments / payload as a JSON-serializable object. */
  args: Record<string, unknown>;
}

/** LLM fallback brief — used if the LLM call fails or is disabled. */
function fallbackBrief(approval: {
  title: string;
  summary: string | null;
  action: string | null;
  amount: number | null;
  risk: string;
  requester: string | null;
}): ApprovalBrief {
  const amountStr =
    approval.amount != null ? ` involving $${approval.amount.toLocaleString()}` : "";
  return {
    why: `${approval.requester ?? "An agent"} is requesting approval to ${approval.action ?? "take action"}${amountStr}. ${approval.summary ?? ""}`.trim(),
    risks: [
      `Risk level classified as ${approval.risk}.`,
      approval.action === "deploy"
        ? "Production deployment may impact live users if it fails."
        : approval.action === "sign_contract"
          ? "Contract execution creates a binding legal obligation."
          : approval.action === "spend"
            ? "Spend authorization commits capital from the operating budget."
            : "Action may have downstream side effects on the autonomous fleet.",
    ],
    ifApproved: `The "${approval.title}" action will proceed and the requesting agent will continue execution.`,
    ifNotApproved: `The "${approval.title}" action will be blocked. The requesting agent will be notified and may escalate or revise the request.`,
    clarifications: [
      {
        q: "Is the action reversible?",
        a:
          approval.action === "deploy"
            ? "Deploy can be rolled back, but traffic may have already hit the new build."
            : approval.action === "sign_contract"
              ? "Signed contracts typically require counterparty agreement to unwind."
              : "Reversibility depends on the action — see the requesting agent for details.",
      },
      {
        q: "What is the financial impact?",
        a:
          approval.amount != null
            ? `Approval commits $${approval.amount.toLocaleString()} of capital.`
            : "No direct financial impact recorded with this request.",
      },
    ],
  };
}

/** Parse the LLM's JSON response into a validated ApprovalBrief (or null on failure). */
function parseBrief(raw: string): ApprovalBrief | null {
  // The LLM may wrap JSON in ```json fences or preamble text. Extract the
  // first balanced {...} block and parse that.
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  const slice = raw.slice(start, end + 1);
  try {
    const obj = JSON.parse(slice);
    const result = ApprovalBriefSchema.safeParse(obj);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

/**
 * Generate a comprehensive owner brief for an approval request.
 *
 * Uses the LLM (via callLLM) to analyze the requested action and
 * produce structured WHY/RISKS/IF-APPROVED/IF-NOT/CLARIFICATIONS output.
 * Falls back to a deterministic template if the LLM is unavailable or
 * returns malformed JSON (mock mode, rate limits, etc.).
 *
 * Does NOT persist the brief — callers must `db.approval.update({ brief })`.
 */
export async function generateApprovalBrief(
  approval: {
    id: string;
    title: string;
    summary: string | null;
    action: string | null;
    amount: number | null;
    risk: string;
    requester: string | null;
  },
  context: BriefContext
): Promise<ApprovalBrief> {
  // Try the real LLM first.
  try {
    const systemPrompt = `You are the approval-brief generator for ARIA Mission Control, an autonomous AI company operations platform. Your job is to produce a concise, structured owner brief for a pending approval so a human operator can decide quickly.

Output ONLY a JSON object with this exact shape (no markdown fences, no preamble):
{
  "why": "1-2 sentences explaining what the agent wants to do and why now.",
  "risks": ["3-5 short risk strings, each one concrete risk"],
  "ifApproved": "1-2 sentences: positive outcomes + immediate next steps if approved.",
  "ifNotApproved": "1-2 sentences: consequences if denied.",
  "clarifications": [{"q": "question the owner might ask", "a": "answer"}, ...2-3 entries]
}

Be specific. Reference the action verb, the amount (if any), and the requesting agent. Never invent unrelated risks. Stay calm and factual.`;

    const prompt = `Generate an approval brief.

Approval record:
- Title: ${approval.title}
- Summary: ${approval.summary ?? "(none)"}
- Action: ${approval.action ?? "(unspecified)"}
- Amount: ${approval.amount != null ? `$${approval.amount.toLocaleString()}` : "(none)"}
- Risk level: ${approval.risk}
- Requester: ${approval.requester ?? "(unknown agent)"}

Action context:
- Agent role: ${context.agentRole}
- Action verb: ${context.action}
- Arguments: ${JSON.stringify(context.args).slice(0, 600)}

Return ONLY the JSON object.`;

    const result = await callLLM("Approval-Brief", "Conductor", prompt, {
      systemOverride: systemPrompt,
      model: "glm-4.5-air",
    });

    if (result.success && result.completion) {
      const parsed = parseBrief(result.completion);
      if (parsed) return parsed;
    }
  } catch (err) {
    logger.warn("approval-brief.generate.error", { id: approval.id, error: String(err) });
  }

  // Fallback — deterministic, never throws.
  return fallbackBrief(approval);
}

/** Serialize a brief to its DB-storable JSON string. */
export function briefToJson(brief: ApprovalBrief): string {
  return JSON.stringify(brief);
}

/** Deserialize a brief from its DB JSON string. Returns null if missing/invalid. */
export function briefFromJson(raw: string | null): ApprovalBrief | null {
  if (!raw) return null;
  return parseJsonObject<ApprovalBrief | null>(raw, null);
}

// ─── Discussion loop ─────────────────────────────────────────────────

/** Read the discussion log from the DB JSON column. */
export function discussionFromJson(raw: string | null): ApprovalDiscussionEntry[] {
  if (!raw) return [];
  return parseJsonArray<ApprovalDiscussionEntry>(raw, []);
}

/** Append a new entry to the discussion log and return the updated JSON string. */
export function appendDiscussion(
  raw: string | null,
  entry: ApprovalDiscussionEntry
): string {
  const list = discussionFromJson(raw);
  list.push(entry);
  return JSON.stringify(list);
}

/**
 * The owner asks a question about a pending approval. The system uses the
 * LLM (with the approval context + prior discussion as history) to answer.
 * Appends both the owner's question and the agent's answer to the
 * `discussionLog` column.
 *
 * Returns the answer + the updated brief JSON (re-persisted on the row).
 */
export async function discussApproval(
  approvalId: string,
  ownerQuestion: string
): Promise<{ answer: string; updatedBrief: string }> {
  const row = await db.approval.findUnique({ where: { id: approvalId } });
  if (!row) {
    throw new Error(`approval ${approvalId} not found`);
  }

  const brief = briefFromJson(row.brief);
  const priorDiscussion = discussionFromJson(row.discussionLog);

  // Build a compact context block for the LLM.
  const briefText = brief
    ? `WHY: ${brief.why}
RISKS: ${brief.risks.join("; ")}
IF APPROVED: ${brief.ifApproved}
IF NOT APPROVED: ${brief.ifNotApproved}
CLARIFICATIONS: ${brief.clarifications.map((c) => `Q: ${c.q} A: ${c.a}`).join(" | ")}`
    : "(no brief generated yet)";

  const historyText = priorDiscussion
    .slice(-6)
    .map((e) => `[${e.role}] ${e.message}`)
    .join("\n");

  let answer: string;
  try {
    const systemPrompt = `You are the ARIA approval-discussion assistant. A human owner is asking a follow-up question about a pending approval. Answer concisely (2-3 sentences), reference the brief data when relevant, and stay factual. If you don't know, say so — never invent details.

Approval context:
- Title: ${row.title}
- Summary: ${row.summary ?? "(none)"}
- Action: ${row.action ?? "(unspecified)"}
- Amount: ${row.amount != null ? `$${row.amount.toLocaleString()}` : "(none)"}
- Risk: ${row.risk}
- Requester: ${row.requester ?? "(unknown)"}

Brief:
${briefText}

Prior discussion:
${historyText || "(none)"}`;

    const result = await callLLM("Approval-Discussion", "Conductor", ownerQuestion, {
      systemOverride: systemPrompt,
      model: "glm-4.5-air",
    });
    answer =
      result.success && result.completion
        ? result.completion.trim()
        : "I couldn't generate an answer right now. The LLM may be unavailable — please try again.";
  } catch (err) {
    logger.warn("approval-brief.discuss.error", { id: approvalId, error: String(err) });
    answer =
      "I couldn't generate an answer right now. Please try again, or decide based on the brief above.";
  }

  // Append owner question + agent answer to the discussion log.
  const now = new Date().toISOString();
  const updated = appendDiscussion(row.discussionLog, {
    role: "owner",
    message: ownerQuestion,
    timestamp: now,
  });
  const updatedWithAnswer = appendDiscussion(updated, {
    role: "agent",
    message: answer,
    timestamp: new Date().toISOString(),
  });

  await db.approval.update({
    where: { id: approvalId },
    data: { discussionLog: updatedWithAnswer },
  });

  return { answer, updatedBrief: updatedWithAnswer };
}

// ─── Oral confirmation ───────────────────────────────────────────────

/**
 * Phrases that count as affirmative oral approval. Lowercased, matched
 * as substrings. The set is conservative — "maybe" / "I think" / "ok"
 * alone do not count (ambiguous). "yes", "approved", "go ahead",
 * "proceed", "do it", "ship it", "make it so", "confirmed", "approve it"
 * all do.
 */
const AFFIRMATIVE_PHRASES = [
  "yes",
  "yeah",
  "yep",
  "yup",
  "approve",
  "approved",
  "approves",
  "approving",
  "go ahead",
  "proceed",
  "do it",
  "do that",
  "ship it",
  "make it so",
  "confirmed",
  "confirm it",
  "ok go",
  "okay go",
  "i approve",
  "i say yes",
  "you're clear",
  "you are clear",
  "green light",
  "sounds good",
  "let's do it",
  "lets do it",
];

/**
 * Negative phrases that override an affirmative ("yes but first..." or
 * "not yet" / "wait" / "deny"). If a negative appears in the same
 * segment as an affirmative, the request is rejected.
 */
const NEGATIVE_PHRASES = [
  "no",
  "nope",
  "not yet",
  "deny",
  "denied",
  "reject",
  "rejected",
  "wait",
  "hold off",
  "hold on",
  "stop",
  "cancel",
  "don't",
  "do not",
  "absolutely not",
  "i refuse",
  "i object",
];

/**
 * Analyze a voice-call transcript to determine if the owner orally
 * approved. Looks for affirmative phrases; if found and no negative
 * override is present, the approval is confirmed.
 *
 * On confirmation:
 *   - Sets `oralConfirmed=true` on the row.
 *   - Sets `status="approved"` + `decidedAt=now()`.
 *   - Appends a `system` entry to the discussion log noting the oral
 *     confirmation.
 *
 * Returns `{ confirmed, reason }` so the caller can surface the decision
 * reason in the API response (e.g. "Affirmative phrase 'yes approved'
 * detected at offset 412").
 */
export async function oralConfirm(
  approvalId: string,
  transcript: string
): Promise<{ confirmed: boolean; reason: string }> {
  const row = await db.approval.findUnique({ where: { id: approvalId } });
  if (!row) {
    throw new Error(`approval ${approvalId} not found`);
  }

  // If the approval is already decided, do not re-confirm.
  if (row.status !== "pending") {
    return {
      confirmed: false,
      reason: `approval is already ${row.status}`,
    };
  }

  const lowered = transcript.toLowerCase();
  const affirmHit = AFFIRMATIVE_PHRASES.find((p) => lowered.includes(p));
  const negativeHit = NEGATIVE_PHRASES.find((p) => lowered.includes(p));

  // Negative override: a negative phrase anywhere in the transcript blocks.
  if (negativeHit && (!affirmHit || lowered.indexOf(negativeHit) < lowered.indexOf(affirmHit))) {
    return {
      confirmed: false,
      reason: `negative phrase '${negativeHit}' detected before any affirmative`,
    };
  }

  if (!affirmHit) {
    return {
      confirmed: false,
      reason: "no affirmative phrase detected in transcript",
    };
  }

  // Confirm — auto-approve.
  const now = new Date().toISOString();
  const updatedLog = appendDiscussion(row.discussionLog, {
    role: "system",
    message: `Oral confirmation detected via voice call. Affirmative phrase: "${affirmHit}". Transcript length: ${transcript.length} chars.`,
    timestamp: now,
  });

  await db.approval.update({
    where: { id: approvalId },
    data: {
      oralConfirmed: true,
      status: "approved",
      decidedAt: new Date(),
      discussionLog: updatedLog,
    },
  });

  // Emit the updated approval through the event bus so the dashboard reflects
  // the auto-approval immediately. Imported lazily to avoid a cycle.
  // (event-bus depends on types.ts; this module also depends on types.ts —
  // safe to lazy-import here.)
  try {
    const { emit } = await import("./event-bus");
    const updated = await db.approval.findUnique({ where: { id: approvalId } });
    if (updated) {
      emit({
        type: "approval",
        ts: now,
        approval: {
          id: updated.id,
          title: updated.title,
          summary: updated.summary,
          risk: updated.risk as ApprovalRisk,
          status: "approved",
          requester: updated.requester,
          agentId: updated.agentId,
          action: updated.action,
          amount: updated.amount,
          payload: updated.payload,
          brief: updated.brief,
          discussionLog: updated.discussionLog,
          oralConfirmed: updated.oralConfirmed,
          voiceCallId: updated.voiceCallId,
          createdAt: toIso(updated.createdAt)!,
          decidedAt: toIso(updated.decidedAt),
        },
      });
    }
  } catch (err) {
    logger.warn("approval-brief.oral-confirm.emit-failed", { id: approvalId, error: String(err) });
  }

  return {
    confirmed: true,
    reason: `oral approval confirmed — affirmative phrase '${affirmHit}' detected`,
  };
}

// ─── Owner notification ──────────────────────────────────────────────

/**
 * Send the approval brief to the owner via Telegram (or trigger a call).
 *
 * Telegram path: uses the existing telegram-notifier to send a Markdown
 * message with the brief contents. Returns true if sent.
 *
 * Call path: this is a stub — when the voice mini-service is wired up,
 * `notifyOwner(approvalId, "call")` would enqueue a call request that
 * the voice service picks up. For now, it logs intent + records the
 * call id on the approval row (so `oralConfirm()` can later be called
 * with the resulting transcript).
 */
export async function notifyOwner(
  approvalId: string,
  channel: "telegram" | "call"
): Promise<{ sent: boolean; channel: string; reason?: string }> {
  const row = await db.approval.findUnique({ where: { id: approvalId } });
  if (!row) {
    return { sent: false, channel, reason: "approval not found" };
  }

  const brief = briefFromJson(row.brief);

  if (channel === "telegram") {
    try {
      const amountStr = row.amount != null ? `\n*Amount:* $${row.amount.toLocaleString()}` : "";
      const risksStr = brief ? `\n*Risks:* ${brief.risks.join(" · ")}` : "";
      const whyStr = brief ? `\n\n_Why:_ ${brief.why}` : "";
      const text = `⏳ *ARIA Approval Brief*\n\n*Title:* ${row.title}\n*Risk:* ${row.risk.toUpperCase()}${amountStr}${risksStr}${whyStr}\n\n_Respond in the dashboard — or say "yes" on a voice call to approve orally._`;
      const ok = await sendTelegramMessage(text);
      return {
        sent: ok,
        channel: "telegram",
        reason: ok ? undefined : "telegram send failed (token/chat-id not configured?)",
      };
    } catch (err) {
      return { sent: false, channel: "telegram", reason: String(err) };
    }
  }

  // Call path — record a synthetic call id for now.
  if (channel === "call") {
    const callId = `call-${approvalId}-${Date.now()}`;
    try {
      await db.approval.update({
        where: { id: approvalId },
        data: { voiceCallId: callId },
      });
      logger.info("approval-brief.notify.call-queued", { id: approvalId, callId });
      return { sent: true, channel: "call" };
    } catch (err) {
      return { sent: false, channel: "call", reason: String(err) };
    }
  }

  return { sent: false, channel, reason: "unknown channel" };
}

// ─── Approval serializer (DB row → API payload) ──────────────────────
/**
 * Convert a Prisma Approval row into the typed `Approval` payload.
 * Centralizes the field mapping so every API route emits the same shape
 * (required by the MissionEventSchema discriminated union).
 */
export function serializeApproval(row: {
  id: string;
  title: string;
  summary: string | null;
  risk: string;
  status: string;
  requester: string | null;
  agentId: string | null;
  action: string | null;
  amount: number | null;
  payload: string | null;
  brief: string | null;
  discussionLog: string | null;
  oralConfirmed: boolean;
  voiceCallId: string | null;
  createdAt: Date;
  decidedAt: Date | null;
}): Approval {
  return {
    id: row.id,
    title: row.title,
    summary: row.summary,
    risk: row.risk as Approval["risk"],
    status: row.status as Approval["status"],
    requester: row.requester,
    agentId: row.agentId,
    action: row.action,
    amount: row.amount,
    payload: row.payload,
    brief: row.brief,
    discussionLog: row.discussionLog,
    oralConfirmed: row.oralConfirmed,
    voiceCallId: row.voiceCallId,
    createdAt: toIso(row.createdAt)!,
    decidedAt: toIso(row.decidedAt),
  };
}
