// =====================================================================
// company-config.ts — Liafon Software Private Limited configuration.
// =====================================================================
// Provides a static company profile + the LIAFON_SERVICES catalog used by
// the ServicesHub tab. Avoids depending on a separate CompanyConfig table
// (which R-1/R-2 may or may not have added). All info is hardcoded here so
// the ServicesHub tab works regardless of DB state.
// =====================================================================

export interface CompanyInfo {
  companyName: string;
  ownerName: string;
  websiteUrl: string;
  watermarkText: string;
  email: string | null;
  phone: string | null;
  address: string | null;
  gstNumber: string | null;
}

export const DEFAULT_COMPANY: CompanyInfo = {
  companyName: 'Liafon Software Private Limited',
  ownerName: 'Raviteja Voruganti',
  websiteUrl: 'https://liafon.com',
  watermarkText: 'Liafon Software Pvt Ltd',
  email: 'contact@liafon.com',
  phone: '+91 90000 00000',
  address: 'Hyderabad, Telangana, India',
  gstNumber: null,
};

export function getCompanyConfig(): CompanyInfo {
  return DEFAULT_COMPANY;
}

export interface LiafonService {
  name: string;
  description: string;
  icon: string;
  price: string;
  category: 'existing' | 'ai';
  featured?: boolean;
}

export const LIAFON_SERVICES: LiafonService[] = [
  {
    name: 'Recruitment & Staffing',
    description:
      'End-to-end recruitment solutions — sourcing, screening, interviewing, and onboarding top talent across IT, finance, and operations.',
    icon: 'Users',
    price: 'Custom',
    category: 'existing',
  },
  {
    name: 'HR Consulting',
    description:
      'HR policy design, payroll management, compliance audits, employee engagement programs, and performance management systems.',
    icon: 'Briefcase',
    price: 'Custom',
    category: 'existing',
  },
  {
    name: 'AI Software Development',
    description:
      'Custom AI-powered web and mobile applications. We build intelligent systems that automate your business processes using LLMs, computer vision, and predictive analytics.',
    icon: 'Code2',
    price: 'From $999',
    category: 'ai',
    featured: true,
  },
  {
    name: '3D Website Design',
    description:
      'Stunning 3D interactive websites with modern animations, glassmorphism, and immersive user experiences. Mobile-responsive, SEO-optimized, and blazing fast.',
    icon: 'Globe',
    price: 'From $499',
    category: 'ai',
    featured: true,
  },
  {
    name: 'AI Marketing Automation',
    description:
      'Autonomous social media management, content generation, SEO optimization, and email marketing campaigns powered by AI agents that work 24/7.',
    icon: 'Megaphone',
    price: 'From $299/mo',
    category: 'ai',
  },
  {
    name: 'AI Chatbot Deployment',
    description:
      'Custom AI chatbots for customer support, lead qualification, and sales. Integrated with your CRM, trained on your data, available 24/7 across web, WhatsApp, and Telegram.',
    icon: 'MessageSquare',
    price: 'From $599',
    category: 'ai',
  },
  {
    name: 'Business Process Automation',
    description:
      'Automate repetitive tasks — data entry, invoice processing, report generation, and workflow routing. Save 20+ hours per week with intelligent automation.',
    icon: 'Settings',
    price: 'From $799',
    category: 'ai',
  },
  {
    name: 'AI-Powered Data Analytics',
    description:
      'Transform raw data into actionable insights. Predictive models, dashboards, and automated reports that help you make data-driven decisions.',
    icon: 'BarChart3',
    price: 'From $499/mo',
    category: 'ai',
  },
  {
    name: 'AI Voice Agent Setup',
    description:
      'IVR systems, AI voice bots, and phone automation that handle inbound calls, route intelligently, and book appointments 24/7. Powered by Twilio + LLM voice models.',
    icon: 'Phone',
    price: 'From $899',
    category: 'ai',
  },
  {
    name: 'AI Video Generation',
    description:
      'Marketing videos, explainer videos, and product demos generated by AI. From script to finished MP4 in hours — voiceover, captions, b-roll, and branding included.',
    icon: 'Video',
    price: 'From $199/video',
    category: 'ai',
  },
  {
    name: 'AI Image Generation',
    description:
      'Logos, marketing graphics, social creatives, and ad assets generated and refined by AI. Brand-consistent, royalty-free, delivered in all formats.',
    icon: 'Image',
    price: 'From $49/asset',
    category: 'ai',
  },
  {
    name: 'AI Content Writing',
    description:
      'Blogs, articles, website copy, and ad copy written by AI and edited by humans. SEO-optimized, plagiarism-free, delivered in your brand voice at scale.',
    icon: 'FileText',
    price: 'From $0.10/word',
    category: 'ai',
  },
  {
    name: 'SEO Optimization',
    description:
      'Technical SEO audits, content SEO strategy, on-page optimization, and authority link building. Rank higher on Google with a data-driven, white-hat approach.',
    icon: 'Search',
    price: 'From $399/mo',
    category: 'ai',
  },
  {
    name: 'Social Media Management',
    description:
      'Full-funnel social media management — content calendar, scheduling, community engagement, and analytics across Instagram, LinkedIn, X, and YouTube.',
    icon: 'Share2',
    price: 'From $599/mo',
    category: 'ai',
  },
  {
    name: 'Email Marketing Automation',
    description:
      'Drip campaigns, segmented sequences, and lifecycle automations that nurture leads and recover carts. Integrated with Klaviyo, Mailchimp, or HubSpot.',
    icon: 'Mail',
    price: 'From $299/mo',
    category: 'ai',
  },
  {
    name: 'CRM Setup & Integration',
    description:
      'HubSpot, Salesforce, or custom CRM setup with full pipeline configuration, contact migration, workflow automation, and team training. Go live in 2 weeks.',
    icon: 'Database',
    price: 'From $1,499',
    category: 'ai',
  },
  {
    name: 'Workflow Automation',
    description:
      'Custom Zapier / Make.com workflows that connect your stack — CRM, email, billing, support, and Slack. Eliminate manual copy-paste forever.',
    icon: 'Workflow',
    price: 'From $499',
    category: 'ai',
  },
  {
    name: 'AI Training & Workshops',
    description:
      'Hands-on team training on AI tools — ChatGPT, Claude, Copilot, and custom LLM workflows. Practical playbooks your team can use the next day.',
    icon: 'GraduationCap',
    price: 'From $999/session',
    category: 'ai',
  },
  {
    name: 'Mobile App Development',
    description:
      'Cross-platform mobile apps in React Native or Flutter — iOS + Android from one codebase. AI-powered features, push notifications, and offline-first.',
    icon: 'Smartphone',
    price: 'From $4,999',
    category: 'ai',
    featured: true,
  },
  {
    name: 'Cloud Migration Consulting',
    description:
      'Migrate workloads to AWS, GCP, or Azure with zero downtime. Architecture design, cost optimization, IaC (Terraform), and 24/7 monitoring included.',
    icon: 'Cloud',
    price: 'From $2,499',
    category: 'ai',
  },
];
