/**
 * src/lib/preview-generator.ts — v65 Phase 15 (Personalized Brand Previews)
 *
 * RULE-52: SHOW, DON'T JUST TELL.
 *
 * Generates personalized service previews using the lead's own brand assets
 * (logo, colors, name). These previews are attached to outreach emails to
 * dramatically increase conversion rates.
 *
 * Example: "Here's how your landing page would look with your logo and colors."
 */

import "server-only";
import { logger } from "./logger";
import type { LeadBrandProfile } from "./brand-extractor";

export interface ServicePreview {
  serviceName: string;
  leadDomain: string;
  html: string;               // styled HTML preview
  previewText: string;        // plain-text description for the email body
  brandProfile: LeadBrandProfile;
  generatedAt: string;
}

/**
 * Generate a personalized service preview with the lead's brand.
 *
 * @param serviceName The ARIA service name (e.g. "Landing Page Generator")
 * @param serviceDescription What the service does
 * @param brand The lead's extracted brand profile
 * @returns A ServicePreview with styled HTML + plain-text description.
 */
export function generatePreview(
  serviceName: string,
  serviceDescription: string,
  brand: LeadBrandProfile,
): ServicePreview {
  const primary = brand.primaryColor ?? "#2563eb";
  const secondary = brand.secondaryColor ?? "#1e40af";
  const accent = brand.accentColor ?? "#3b82f6";
  const logoUrl = brand.logoUrl ?? "";
  const domain = brand.domain;
  const tone = brand.brandTone ?? "professional";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${serviceName} — Preview for ${domain}</title>
  <style>
    :root {
      --brand-primary: ${primary};
      --brand-secondary: ${secondary};
      --brand-accent: ${accent};
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: ${brand.typography ?? "system-ui, -apple-system, sans-serif"}; background: #f8fafc; color: #1e293b; }
    .header { background: var(--brand-primary); color: white; padding: 2rem; text-align: center; }
    .header img { max-height: 60px; margin-bottom: 1rem; }
    .header h1 { font-size: 1.5rem; font-weight: 700; }
    .header p { font-size: 0.9rem; opacity: 0.9; margin-top: 0.5rem; }
    .container { max-width: 600px; margin: 2rem auto; padding: 0 1rem; }
    .card { background: white; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); padding: 2rem; margin-bottom: 1.5rem; }
    .card h2 { color: var(--brand-secondary); font-size: 1.2rem; margin-bottom: 0.5rem; }
    .card p { font-size: 0.95rem; line-height: 1.6; color: #475569; }
    .cta { display: inline-block; background: var(--brand-accent); color: white; padding: 0.75rem 1.5rem; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 1rem; }
    .badge { display: inline-block; background: var(--brand-primary); color: white; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
    .footer { text-align: center; padding: 2rem; color: #94a3b8; font-size: 0.8rem; }
    .preview-notice { background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 1rem; margin-bottom: 1.5rem; font-size: 0.85rem; color: #92400e; }
  </style>
</head>
<body>
  <div class="preview-notice">
    🎨 <strong>Personalized Preview</strong> — This is how "${serviceName}" would look with ${domain}'s brand assets (colors: ${primary}, ${accent}).
  </div>

  <div class="header">
    ${logoUrl ? `<img src="${logoUrl}" alt="${domain} logo" onerror="this.style.display='none'">` : ""}
    <h1>${serviceName}</h1>
    <p>Powered by ARIA Mission Control — personalized for ${domain}</p>
  </div>

  <div class="container">
    <div class="card">
      <span class="badge">${tone}</span>
      <h2>What we'll build for you</h2>
      <p>${serviceDescription}</p>
      <a href="#" class="cta">Get Started →</a>
    </div>

    <div class="card">
      <h2>Your Brand Applied</h2>
      <p><strong>Primary color:</strong> <span style="display:inline-block;width:12px;height:12px;background:${primary};border-radius:2px;vertical-align:middle;"></span> ${primary}</p>
      <p><strong>Secondary color:</strong> <span style="display:inline-block;width:12px;height:12px;background:${secondary};border-radius:2px;vertical-align:middle;"></span> ${secondary}</p>
      <p><strong>Accent color:</strong> <span style="display:inline-block;width:12px;height:12px;background:${accent};border-radius:2px;vertical-align:middle;"></span> ${accent}</p>
      <p><strong>Typography:</strong> ${brand.typography ?? "system-ui"}</p>
      <p><strong>Tone:</strong> ${tone}</p>
    </div>
  </div>

  <div class="footer">
    This preview was automatically generated by ARIA Mission Control using ${domain}'s brand assets.<br>
    Ready to launch? Reply to this email to get started.
  </div>
</body>
</html>`;

  const previewText = `We've already prepared a personalized preview of "${serviceName}" with ${domain}'s brand:
  • Primary color: ${primary}
  • Accent color: ${accent}
  • Brand tone: ${tone}
  • Typography: ${brand.typography ?? "system-ui"}

The attached HTML preview shows exactly how your service would look with your logo and colors applied. No generic templates — this is YOUR brand, ready to launch.`;

  logger.info("preview-generator.complete", { serviceName, domain, primary });

  return {
    serviceName,
    leadDomain: domain,
    html,
    previewText,
    brandProfile: brand,
    generatedAt: new Date().toISOString(),
  };
}
