import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const VALID_STATUSES = ['open', 'acknowledged', 'resolved', 'dismissed'];

// ─── PATCH /api/agent-monitors/findings/[id] ──────────────────────────
// Update a finding's status. If status=resolved and no linkedTaskId, the
// caller may also pass `{ createTask: true }` to auto-create a Task.
export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  let body: Record<string, unknown> = {};
  try {
    body = (await req.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ ok: false, error: 'invalid-json' }, { status: 400 });
  }

  const status = typeof body.status === 'string' ? body.status : null;
  if (!status || !VALID_STATUSES.includes(status)) {
    return NextResponse.json(
      { ok: false, error: `invalid-status:${status ?? 'null'}` },
      { status: 400 },
    );
  }

  const existing = await db.agentMonitorFinding.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ ok: false, error: 'not-found' }, { status: 404 });
  }

  const updateData: Record<string, unknown> = { status };
  let createdTaskId: string | null = null;

  // If resolving and caller wants a Task created and none linked yet.
  if (
    status === 'resolved' &&
    !existing.linkedTaskId &&
    body.createTask === true
  ) {
    const newTask = await createTaskFromFinding(existing);
    if (newTask) {
      updateData.linkedTaskId = newTask.id;
      createdTaskId = newTask.id;
    }
  }

  const updated = await db.agentMonitorFinding.update({
    where: { id },
    data: updateData,
  });

  return NextResponse.json({
    ok: true,
    finding: {
      ...updated,
      evidence: safeParseJson(updated.evidence, {}),
      actionMeta: safeParseJson(updated.actionMeta, {}),
    },
    createdTaskId,
  });
}

async function createTaskFromFinding(finding: {
  title: string;
  detail: string;
  severity: string;
  category: string;
  tab: string;
}) {
  const priorityMap: Record<string, string> = {
    critical: 'critical',
    error: 'high',
    warn: 'medium',
    info: 'low',
  };
  const priority = priorityMap[finding.severity] ?? 'medium';
  const description = `${finding.detail}\n\n— Auto-generated by ${finding.category} monitor on tab "${finding.tab}".`;
  try {
    const task = await db.task.create({
      data: {
        title: finding.title.slice(0, 200),
        description,
        status: 'pending',
        priority,
        tags: JSON.stringify(['agent-monitor', finding.category, finding.tab]),
      },
    });
    return task;
  } catch (err) {
    console.error('[agent-monitors] createTaskFromFinding failed:', err);
    return null;
  }
}

function safeParseJson<T>(raw: string, fallback: T): T {
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}
