import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// ─── POST /api/agent-monitors/findings/[id]/create-task ──────────────
// Creates a Task from a finding (title from finding.title, description from
// detail, priority from severity, tags from category). Links the finding's
// `linkedTaskId` so subsequent status updates can be tracked.
export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;

  const finding = await db.agentMonitorFinding.findUnique({ where: { id } });
  if (!finding) {
    return NextResponse.json({ ok: false, error: 'not-found' }, { status: 404 });
  }

  // If a task is already linked, return it (idempotent).
  if (finding.linkedTaskId) {
    const existing = await db.task.findUnique({ where: { id: finding.linkedTaskId } });
    if (existing) {
      return NextResponse.json({
        ok: true,
        task: existing,
        findingId: finding.id,
        message: 'Task already linked — returning existing task.',
      });
    }
  }

  const priorityMap: Record<string, string> = {
    critical: 'critical',
    error: 'high',
    warn: 'medium',
    info: 'low',
  };
  const priority = priorityMap[finding.severity] ?? 'medium';
  const description = `${finding.detail}\n\n— Auto-generated by monitor "${finding.monitorKey}" (category: ${finding.category}) for tab "${finding.tab}".\nFinding ID: ${finding.id}\nCreated: ${finding.createdAt.toISOString()}`;

  try {
    const task = await db.task.create({
      data: {
        title: finding.title.slice(0, 200),
        description,
        status: 'pending',
        priority,
        tags: JSON.stringify([
          'agent-monitor',
          finding.category,
          finding.tab,
          finding.monitorKey,
        ]),
      },
    });

    await db.agentMonitorFinding.update({
      where: { id: finding.id },
      data: { linkedTaskId: task.id, status: 'acknowledged' },
    });

    // Also create a notification so the operator sees it.
    await db.notification.create({
      data: {
        type: 'success',
        title: 'Task created from monitor finding',
        message: `Task "${task.title}" created from "${finding.monitorKey}" finding. Priority: ${priority}.`,
        read: false,
      },
    });

    return NextResponse.json(
      {
        ok: true,
        task,
        findingId: finding.id,
        message: 'Task created + finding acknowledged.',
      },
      { status: 201 },
    );
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }
}
